{
 "title": "Electrical",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS \"time\", avg(value) AS \"Voltage\" FROM signalk WHERE path LIKE 'electrical.batteries.%.voltage' AND context = 'self' AND ts >= $__timeFrom() AND ts <= $__timeTo() SAMPLE BY 10s"
    }
   ]
  },
  {
   "title": "Battery Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS \"time\", avg(value) AS \"Current\" FROM signalk WHERE path LIKE 'electrical.batteries.%.current' AND context = 'self' AND ts >= $__timeFrom() AND ts <= $__timeTo() SAMPLE BY 10s"
    }
   ]
  },
  {
   "title": "AC Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS \"time\", avg(value) AS \"Power\" FROM signalk WHERE path LIKE 'electrical.ac.%.total.realPower' AND context = 'self' AND ts >= $__timeFrom() AND ts <= $__timeTo() SAMPLE BY 10s"
    }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS \"time\", avg(value) AS \"Voltage\" FROM signalk WHERE path LIKE 'electrical.ac.%.average.lineNeutralVoltage' AND context = 'self' AND ts >= $__timeFrom() AND ts <= $__timeTo() SAMPLE BY 10s"
    }
   ]
  }
 ]
}