{
 "title": "Environment",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS \"time\", avg(value) * 1.94384 AS \"AWS\" FROM signalk WHERE path = 'environment.wind.speedApparent' AND context = 'self' AND ts >= $__timeFrom() AND ts <= $__timeTo() SAMPLE BY 10s"
    }
   ]
  },
  {
   "title": "Wind Angle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS \"time\", avg(value) * 57.2958 AS \"AWA\" FROM signalk WHERE path = 'environment.wind.angleApparent' AND context = 'self' AND ts >= $__timeFrom() AND ts <= $__timeTo() SAMPLE BY 10s"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS \"time\", avg(value) / 100 AS \"Baro\" FROM signalk WHERE path = 'environment.outside.pressure' AND context = 'self' AND ts >= $__timeFrom() AND ts <= $__timeTo() SAMPLE BY 10s"
    }
   ]
  },
  {
   "title": "Water Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS \"time\", avg(value) - 273.15 AS \"Water\" FROM signalk WHERE path = 'environment.water.temperature' AND context = 'self' AND ts >= $__timeFrom() AND ts <= $__timeTo() SAMPLE BY 10s"
    }
   ]
  }
 ]
}