{
 "title": "Navigation",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Speed Over Ground",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS time, avg(value) * 1.94384 AS \"SOG\" FROM signalk WHERE path = 'navigation.speedOverGround' AND context = 'self' AND $__timeFilter(ts) SAMPLE BY $__interval"
    }
   ]
  },
  {
   "title": "Course Over Ground",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS time, avg(value) * 57.2958 AS \"COG\" FROM signalk WHERE path = 'navigation.courseOverGroundTrue' AND context = 'self' AND $__timeFilter(ts) SAMPLE BY $__interval"
    }
   ]
  },
  {
   "title": "Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS time, avg(value) AS \"Depth\" FROM signalk WHERE path = 'environment.depth.belowTransducer' AND context = 'self' AND $__timeFilter(ts) SAMPLE BY $__interval"
    }
   ]
  },
  {
   "title": "Heading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS time, avg(value) * 57.2958 AS \"Heading\" FROM signalk WHERE path = 'navigation.headingTrue' AND context = 'self' AND $__timeFilter(ts) SAMPLE BY $__interval"
    }
   ]
  }
 ]
}